name: "Astro Deploy"
description: "A composite action that prepares your Astro site to be deployed to GitHub Pages"
branding:
  icon: "box"
  color: "orange"
inputs:
  path:
    description: "Path of the directory containing your site"
    required: false
    default: "."
  node-version:
    description: "The node version to use"
    required: false
    default: "16"
  package-manager:
    description: "If not automatically detectable, you may specify your preferred package manager"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Check lockfiles
      id: lockfile
      shell: "bash"
      env:
        INPUT_PM: ${{ inputs.package-manager }}
      run: |
        len=`echo $INPUT_PM | wc -c`
        if [ $len -gt 1 ]; then
            echo "PACKAGE_MANAGER=$INPUT_PM" >> $GITHUB_OUTPUT
            echo "node_pm=$INPUT_PM" >> $GITHUB_ENV
        elif [ $(find "." -name "pnpm-lock.yaml") ]; then
            echo "PACKAGE_MANAGER=pnpm" >> $GITHUB_OUTPUT
            echo "node_pm=pnpm" >> $GITHUB_ENV
        elif [ $(find "." -name "yarn.lock") ]; then 
            echo "PACKAGE_MANAGER=yarn" >> $GITHUB_OUTPUT
            echo "node_pm=yarn" >> $GITHUB_ENV
        elif [ $(find "." -name "package-lock.json") ]; then 
            echo "PACKAGE_MANAGER=npm" >> $GITHUB_OUTPUT
            echo "node_pm=npm" >> $GITHUB_ENV
        else
            echo "No lockfile found.
        Please specify your preferred \"package-manager\" in the action configuration."
            exit 1
        fi

    - name: Setup PNPM
      if: ${{ steps.lockfile.outputs.PACKAGE_MANAGER == 'pnpm' }}
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 7.x.x

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ steps.lockfile.outputs.PACKAGE_MANAGER }}

    - name: Install
      shell: "bash"
      run: |
        cd ${{ inputs.path }}
        $node_pm install

    - name: Build
      shell: "bash"
      env:
        PACKAGE_MANAGER: ${{ steps.lockfile.outputs.PACKAGE_MANAGER }}
      run: |
        cd ${{ inputs.path }}
        $node_pm run build

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: "${{ inputs.path }}/dist/"
